# Generated by Django 4.2.26 on 2025-11-27 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_de', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_pt', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('body_ru', models.TextField(null=True, verbose_name='Body')),
                ('body_en', models.TextField(null=True, verbose_name='Body')),
                ('body_de', models.TextField(null=True, verbose_name='Body')),
                ('body_pt', models.TextField(null=True, verbose_name='Body')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='news/archives/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'News Post',
                'verbose_name_plural': 'News Posts',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='news/media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=20)),
                ('original_name', models.CharField(help_text='Original filename in the zip', max_length=255)),
                ('news_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='news.newspost')),
            ],
        ),
    ]
