# Generated by Django 4.2.26 on 2025-12-11 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=news.models.media_upload_path, verbose_name='File')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=20, verbose_name='Media Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Media Upload',
                'verbose_name_plural': 'Media Uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
