# Generated by Django 4.2.26 on 2025-12-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_mediaupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], max_length=20, verbose_name='Media Type'),
        ),
    ]
