# Generated by Django 4.2.26 on 2025-12-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_mediaupload_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='draft', help_text='Draft: не опубликовано, Scheduled: запланировано, Published: опубликовано', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='newspost',
            index=models.Index(fields=['status', '-pub_date'], name='news_newspo_status_7c5698_idx'),
        ),
    ]
