# Generated by Django 4.2.26 on 2025-12-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newspost_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='source_language',
            field=models.CharField(default='ru', help_text='Исходный язык новости (ru, en, de, pt)', max_length=10, verbose_name='Source Language'),
        ),
    ]
