# Generated by Django 4.2.26 on 2026-01-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_newsdiscoverystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='is_no_news_found',
            field=models.BooleanField(default=False, help_text="Пометка для записей 'новостей не найдено'. Используется для фильтрации и массового удаления на фронтенде.", verbose_name='No News Found'),
        ),
    ]
