# Generated by Django 4.2.26 on 2026-01-07 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_add_manufacturer_statistics'),
        ('news', '0010_add_is_no_news_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Производитель, по которому была найдена новость', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to='references.manufacturer', verbose_name='Manufacturer'),
        ),
    ]
