# Generated by Django 4.2.26 on 2026-01-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_add_manufacturer_to_newspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdiscoverystatus',
            name='search_type',
            field=models.CharField(choices=[('resources', 'Resources'), ('manufacturers', 'Manufacturers')], default='resources', help_text='Тип поиска: источники или производители', max_length=20, verbose_name='Search Type'),
        ),
        migrations.AlterField(
            model_name='newsdiscoverystatus',
            name='processed_count',
            field=models.IntegerField(default=0, help_text='Количество обработанных источников/производителей', verbose_name='Processed Count'),
        ),
        migrations.AlterField(
            model_name='newsdiscoverystatus',
            name='total_count',
            field=models.IntegerField(default=0, help_text='Общее количество источников/производителей для обработки', verbose_name='Total Count'),
        ),
        migrations.AddIndex(
            model_name='newsdiscoverystatus',
            index=models.Index(fields=['search_type', 'status'], name='news_newsdi_search__20f376_idx'),
        ),
    ]
