# Generated by Django 4.2.26 on 2026-01-15 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_add_language_to_newsresource'),
        ('news', '0013_add_provider_to_discovery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryAPICall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text='Провайдер LLM', max_length=20, verbose_name='Provider')),
                ('model', models.CharField(help_text='Использованная модель', max_length=50, verbose_name='Model')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='Input Tokens')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='Output Tokens')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Cost (USD)')),
                ('duration_ms', models.IntegerField(default=0, help_text='Время выполнения запроса в миллисекундах', verbose_name='Duration (ms)')),
                ('success', models.BooleanField(default=True, verbose_name='Success')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error Message')),
                ('news_extracted', models.IntegerField(default=0, help_text='Количество новостей, извлечённых из этого запроса', verbose_name='News Extracted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Discovery API Call',
                'verbose_name_plural': 'Discovery API Calls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', help_text='Название конфигурации для идентификации', max_length=100, verbose_name='Configuration Name')),
                ('is_active', models.BooleanField(default=False, help_text='Только одна конфигурация может быть активной', verbose_name='Is Active')),
                ('primary_provider', models.CharField(choices=[('grok', 'Grok (xAI)'), ('anthropic', 'Anthropic Claude'), ('gemini', 'Google Gemini'), ('openai', 'OpenAI GPT')], default='grok', help_text='Основной провайдер для поиска', max_length=20, verbose_name='Primary Provider')),
                ('fallback_chain', models.JSONField(blank=True, default=list, help_text="Цепочка резервных провайдеров: ['anthropic', 'gemini', 'openai']", verbose_name='Fallback Chain')),
                ('temperature', models.FloatField(default=0.3, help_text='Температура LLM (0.0-1.0). Меньше = более детерминированный', verbose_name='Temperature')),
                ('timeout', models.IntegerField(default=120, help_text='Таймаут запроса к LLM в секундах', verbose_name='Timeout (seconds)')),
                ('max_search_results', models.IntegerField(default=5, help_text='Макс. количество результатов веб-поиска Grok (влияет на стоимость!)', verbose_name='Max Search Results')),
                ('search_context_size', models.CharField(choices=[('low', 'Low (минимальный контекст, дешевле)'), ('medium', 'Medium (баланс)'), ('high', 'High (максимальный контекст, дороже)')], default='low', help_text='Размер контекста для веб-поиска', max_length=10, verbose_name='Search Context Size')),
                ('grok_model', models.CharField(default='grok-4-1-fast', help_text='Модель Grok (xAI)', max_length=50, verbose_name='Grok Model')),
                ('anthropic_model', models.CharField(default='claude-3-5-haiku-20241022', help_text='Модель Anthropic Claude', max_length=50, verbose_name='Anthropic Model')),
                ('gemini_model', models.CharField(default='gemini-2.0-flash-exp', help_text='Модель Google Gemini', max_length=50, verbose_name='Gemini Model')),
                ('openai_model', models.CharField(default='gpt-4o', help_text='Модель OpenAI GPT', max_length=50, verbose_name='OpenAI Model')),
                ('max_news_per_resource', models.IntegerField(default=10, help_text='Максимум новостей с одного источника за один поиск', verbose_name='Max News Per Resource')),
                ('delay_between_requests', models.FloatField(default=0.5, help_text='Задержка между запросами к API в секундах', verbose_name='Delay Between Requests (seconds)')),
                ('grok_input_price', models.DecimalField(decimal_places=4, default=3.0, help_text='Цена за 1М входных токенов Grok в USD', max_digits=10, verbose_name='Grok Input Price (per 1M tokens)')),
                ('grok_output_price', models.DecimalField(decimal_places=4, default=15.0, help_text='Цена за 1М выходных токенов Grok в USD', max_digits=10, verbose_name='Grok Output Price (per 1M tokens)')),
                ('anthropic_input_price', models.DecimalField(decimal_places=4, default=0.8, help_text='Цена за 1М входных токенов Anthropic в USD', max_digits=10, verbose_name='Anthropic Input Price (per 1M tokens)')),
                ('anthropic_output_price', models.DecimalField(decimal_places=4, default=4.0, help_text='Цена за 1М выходных токенов Anthropic в USD', max_digits=10, verbose_name='Anthropic Output Price (per 1M tokens)')),
                ('gemini_input_price', models.DecimalField(decimal_places=4, default=0.075, help_text='Цена за 1М входных токенов Gemini в USD', max_digits=10, verbose_name='Gemini Input Price (per 1M tokens)')),
                ('gemini_output_price', models.DecimalField(decimal_places=4, default=0.3, help_text='Цена за 1М выходных токенов Gemini в USD', max_digits=10, verbose_name='Gemini Output Price (per 1M tokens)')),
                ('openai_input_price', models.DecimalField(decimal_places=4, default=2.5, help_text='Цена за 1М входных токенов OpenAI в USD', max_digits=10, verbose_name='OpenAI Input Price (per 1M tokens)')),
                ('openai_output_price', models.DecimalField(decimal_places=4, default=10.0, help_text='Цена за 1М выходных токенов OpenAI в USD', max_digits=10, verbose_name='OpenAI Output Price (per 1M tokens)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Search Configuration',
                'verbose_name_plural': 'Search Configurations',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='newsdiscoveryrun',
            options={'ordering': ['-created_at'], 'verbose_name': 'News Discovery Run', 'verbose_name_plural': 'News Discovery Runs'},
        ),
        migrations.AddField(
            model_name='newsdiscoveryrun',
            name='config_snapshot',
            field=models.JSONField(blank=True, help_text='Копия конфигурации на момент запуска поиска', null=True, verbose_name='Config Snapshot'),
        ),
        migrations.AddField(
            model_name='newsdiscoveryrun',
            name='estimated_cost_usd',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Расчётная стоимость в USD', max_digits=10, verbose_name='Estimated Cost (USD)'),
        ),
        migrations.AddField(
            model_name='newsdiscoveryrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='Время завершения поиска', null=True, verbose_name='Finished At'),
        ),
        migrations.AddField(
            model_name='newsdiscoveryrun',
            name='news_duplicates',
            field=models.IntegerField(default=0, help_text='Количество дубликатов (пропущенных)', verbose_name='News Duplicates'),
        ),
        migrations.AddField(
            model_name='newsdiscoveryrun',
            name='news_found',
            field=models.IntegerField(default=0, help_text='Количество найденных новостей', verbose_name='News Found'),
        ),
        migrations.AddField(
            model_name='newsdiscoveryrun',
            name='provider_stats',
            field=models.JSONField(blank=True, default=dict, help_text='Статистика по провайдерам: {provider: {requests, input_tokens, output_tokens, cost, errors}}', verbose_name='Provider Stats'),
        ),
        migrations.AddField(
            model_name='newsdiscoveryrun',
            name='resources_failed',
            field=models.IntegerField(default=0, help_text='Количество ресурсов с ошибками', verbose_name='Resources Failed'),
        ),
        migrations.AddField(
            model_name='newsdiscoveryrun',
            name='resources_processed',
            field=models.IntegerField(default=0, help_text='Количество обработанных ресурсов', verbose_name='Resources Processed'),
        ),
        migrations.AddField(
            model_name='newsdiscoveryrun',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Время начала поиска', null=True, verbose_name='Started At'),
        ),
        migrations.AddField(
            model_name='newsdiscoveryrun',
            name='total_input_tokens',
            field=models.IntegerField(default=0, help_text='Общее количество входных токенов', verbose_name='Total Input Tokens'),
        ),
        migrations.AddField(
            model_name='newsdiscoveryrun',
            name='total_output_tokens',
            field=models.IntegerField(default=0, help_text='Общее количество выходных токенов', verbose_name='Total Output Tokens'),
        ),
        migrations.AddField(
            model_name='newsdiscoveryrun',
            name='total_requests',
            field=models.IntegerField(default=0, help_text='Общее количество запросов к API', verbose_name='Total Requests'),
        ),
        migrations.AddIndex(
            model_name='newsdiscoveryrun',
            index=models.Index(fields=['-created_at'], name='news_newsdi_created_e51959_idx'),
        ),
        migrations.AddField(
            model_name='discoveryapicall',
            name='discovery_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_calls', to='news.newsdiscoveryrun', verbose_name='Discovery Run'),
        ),
        migrations.AddField(
            model_name='discoveryapicall',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_calls', to='references.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='discoveryapicall',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_calls', to='references.newsresource', verbose_name='Resource'),
        ),
        migrations.AddIndex(
            model_name='discoveryapicall',
            index=models.Index(fields=['discovery_run', '-created_at'], name='news_discov_discove_a6f785_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveryapicall',
            index=models.Index(fields=['provider', '-created_at'], name='news_discov_provide_5556e9_idx'),
        ),
    ]
