# Generated by Django 4.2.26 on 2026-01-15 13:15

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_search_configuration_and_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdiscoveryrun',
            name='last_search_date',
            field=models.DateField(default=news.models.get_today_date, help_text='Дата последнего успешного поиска новостей', verbose_name='Last Search Date'),
        ),
    ]
