# Generated by Django 4.2.26 on 2025-12-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('message', models.TextField(max_length=2000, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_processed', models.BooleanField(default=False, help_text='Mark as processed after admin review', verbose_name='Is Processed')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
