"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.26.
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Parse ALLOWED_HOSTS from environment or use defaults
_allowed_hosts_str = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,hvac-news.ngrok.io,finance.ngrok.app,hvac-news.online,www.hvac-news.online')
ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts_str.split(',') if host.strip()]
# For development, allow all hosts if DEBUG is True
if DEBUG:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'modeltranslation',  # Must be before admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    # Local apps
    'users',
    'references',
    'news',
    'feedback',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Locale middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.postgresql')
DB_NAME = os.getenv('DB_NAME', 'hvac_db')

DATABASES = {
    'default': {
        'ENGINE': DB_ENGINE,
        'NAME': DB_NAME,
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Supported languages
LANGUAGES = [
    ('ru', 'Russian'),
    ('en', 'English'),
    ('de', 'German'),
    ('pt', 'Portuguese'),
]

MODELTRANSLATION_DEFAULT_LANGUAGE = 'ru'
# По умолчанию для всех языков искать в ru, потом en
# Можно настроить более тонко для каждого языка, если потребуется (через MODELTRANSLATION_FALLBACK_LANGUAGES словарь)
MODELTRANSLATION_FALLBACK_LANGUAGES = {
    'default': ('ru', 'en'),
    'ru': ('en',),
    'en': ('ru',),
    'de': ('en', 'ru'),
    'pt': ('en', 'ru'),
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}

# JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',
}

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True  # For development only
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'ngrok-skip-browser-warning',
    'bypass-tunnel-reminder',
]

# CSRF Configuration
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://*.loca.lt',
    'https://*.ngrok-free.app',
    'https://*.ngrok.io',
    'https://hvac-news.ngrok.io',
    'https://finance.ngrok.app',
    'https://*.trycloudflare.com',
    'https://hvac-news.trycloudflare.com',
    'https://*.figma.site',
    'https://*.figma.com',
    'https://hvac-news.online',
    'https://www.hvac-news.online',
]

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@hvacnews.com')
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', 'admin@hvacnews.com')

# CAPTCHA Configuration
CAPTCHA_TYPE = os.getenv('CAPTCHA_TYPE', 'hcaptcha')  # 'hcaptcha' or 'recaptcha'
HCAPTCHA_SECRET_KEY = os.getenv('HCAPTCHA_SECRET_KEY', '')
RECAPTCHA_SECRET_KEY = os.getenv('RECAPTCHA_SECRET_KEY', '')

# Translation Configuration
TRANSLATION_PROVIDER = os.getenv('TRANSLATION_PROVIDER', 'openai')  # 'openai', 'anthropic', 'deepl'
TRANSLATION_API_KEY = os.getenv('TRANSLATION_API_KEY', '')
TRANSLATION_MODEL = os.getenv('TRANSLATION_MODEL', 'gpt-4o-mini')  # OpenAI model
TRANSLATION_ENABLED = os.getenv('TRANSLATION_ENABLED', 'True') == 'True'

# News Discovery Configuration
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', 'AIzaSyC0jX3-k6XUwFQ8DrdY3EwzKfaf22uLiFk')
NEWS_DISCOVERY_OPENAI_MODEL = os.getenv('NEWS_DISCOVERY_OPENAI_MODEL', 'gpt-5.2')  # GPT-5.2 Thinking для Chat Completions API (gpt-5.2-pro только в Responses API)
NEWS_DISCOVERY_GEMINI_MODEL = os.getenv('NEWS_DISCOVERY_GEMINI_MODEL', 'gemini-3-pro-preview')  # Gemini 3 Pro с поддержкой веб-поиска
NEWS_DISCOVERY_TIMEOUT = int(os.getenv('NEWS_DISCOVERY_TIMEOUT', '120'))  # Таймаут в секундах

# Grok (xAI) Configuration
XAI_API_KEY = os.getenv('XAI_API_KEY', 'YOUR_XAI_API_KEY')
NEWS_DISCOVERY_GROK_MODEL = os.getenv('NEWS_DISCOVERY_GROK_MODEL', 'grok-4-1-fast')  # Grok 4.1 Fast с веб-поиском
NEWS_DISCOVERY_USE_GROK = os.getenv('NEWS_DISCOVERY_USE_GROK', 'True') == 'True'  # Использовать Grok вместо OpenAI
NEWS_DISCOVERY_USE_OPENAI_FALLBACK = os.getenv('NEWS_DISCOVERY_USE_OPENAI_FALLBACK', 'True') == 'True'  # Использовать OpenAI как резервный вариант
