# Generated by Django 4.2.26 on 2025-12-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresource',
            name='section',
            field=models.CharField(blank=True, help_text='Section/region name from the resources file', max_length=255, verbose_name='Section'),
        ),
    ]
