# Generated by Django 4.2.26 on 2026-01-07 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_newsresource_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsResourceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_news_found', models.IntegerField(default=0, help_text='Всего найдено новостей за все время', verbose_name='Total News Found')),
                ('total_searches', models.IntegerField(default=0, help_text='Всего выполнено поисков', verbose_name='Total Searches')),
                ('total_no_news', models.IntegerField(default=0, help_text="Всего раз 'новостей не найдено'", verbose_name='Total No News')),
                ('total_errors', models.IntegerField(default=0, help_text='Всего ошибок при поиске', verbose_name='Total Errors')),
                ('last_search_date', models.DateTimeField(blank=True, help_text='Дата и время последнего поиска', null=True, verbose_name='Last Search Date')),
                ('last_news_date', models.DateTimeField(blank=True, help_text='Дата и время последней найденной новости', null=True, verbose_name='Last News Date')),
                ('first_search_date', models.DateTimeField(blank=True, help_text='Дата и время первого поиска', null=True, verbose_name='First Search Date')),
                ('success_rate', models.FloatField(default=0.0, help_text='Процент успешных поисков (найдено новостей) в процентах', verbose_name='Success Rate')),
                ('error_rate', models.FloatField(default=0.0, help_text='Процент ошибок в процентах', verbose_name='Error Rate')),
                ('avg_news_per_search', models.FloatField(default=0.0, help_text='Среднее количество новостей за один поиск', verbose_name='Average News Per Search')),
                ('news_last_30_days', models.IntegerField(default=0, help_text='Количество новостей за последние 30 дней', verbose_name='News Last 30 Days')),
                ('news_last_90_days', models.IntegerField(default=0, help_text='Количество новостей за последние 90 дней', verbose_name='News Last 90 Days')),
                ('searches_last_30_days', models.IntegerField(default=0, help_text='Количество поисков за последние 30 дней', verbose_name='Searches Last 30 Days')),
                ('ranking_score', models.FloatField(default=0.0, help_text='Общий рейтинг для сортировки (чем выше, тем лучше)', verbose_name='Ranking Score')),
                ('priority', models.IntegerField(default=0, help_text='Приоритет обработки (чем выше, тем раньше обрабатывать)', verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли источник (есть новости за последние 90 дней)', verbose_name='Is Active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='references.newsresource', verbose_name='Resource')),
            ],
            options={
                'verbose_name': 'News Resource Statistics',
                'verbose_name_plural': 'News Resources Statistics',
                'ordering': ['-ranking_score', '-total_news_found'],
                'indexes': [models.Index(fields=['-ranking_score'], name='references__ranking_a03493_idx'), models.Index(fields=['is_active', '-ranking_score'], name='references__is_acti_d6fd05_idx'), models.Index(fields=['-total_news_found'], name='references__total_n_1ff2ad_idx')],
            },
        ),
    ]
