# Generated by Django 4.2.26 on 2026-01-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_add_manufacturer_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresource',
            name='custom_search_instructions',
            field=models.TextField(blank=True, help_text="Специальные инструкции для LLM по поиску новостей на этом источнике. Используется для источников типа 'hybrid'. Если пусто - используется стандартный промпт.", verbose_name='Custom Search Instructions'),
        ),
        migrations.AddField(
            model_name='newsresource',
            name='source_type',
            field=models.CharField(choices=[('auto', 'Автоматический поиск'), ('manual', 'Ручной ввод'), ('hybrid', 'Гибридный (с кастомными инструкциями)')], default='auto', help_text='Тип источника: auto - автоматический поиск LLM, manual - только ручной ввод, hybrid - автопоиск с кастомными инструкциями', max_length=20, verbose_name='Source Type'),
        ),
    ]
