# Generated by Django 4.2.26 on 2026-01-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_add_source_type_to_newsresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresource',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Служебные заметки о источнике. Видны только администраторам. Используйте для хранения служебной информации, замечаний, проблем и т.д.', verbose_name='Internal Notes'),
        ),
    ]
