# Generated by Django 4.2.26 on 2026-01-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_add_internal_notes_to_newsresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsresource',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian (Русский)'), ('en', 'English (Английский)'), ('es', 'Spanish (Испанский)'), ('de', 'German (Немецкий)'), ('pt', 'Portuguese (Португальский)'), ('fr', 'French (Французский)'), ('it', 'Italian (Итальянский)'), ('tr', 'Turkish (Турецкий)'), ('ar', 'Arabic (Арабский)'), ('zh', 'Chinese (Китайский)'), ('ja', 'Japanese (Японский)'), ('ko', 'Korean (Корейский)'), ('pl', 'Polish (Польский)'), ('nl', 'Dutch (Голландский)'), ('sv', 'Swedish (Шведский)'), ('other', 'Other (Другой)')], default='en', help_text='Язык контента источника. Используется для генерации промпта на соответствующем языке.', max_length=10, verbose_name='Language'),
        ),
    ]
